version: '3'

volumes:
  maag_app_local_postgres_data: {}
  maag_app_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: maag_app_local_django
    container_name: maag_app_local_django
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start
    networks:
      - maag-network

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: maag_app_production_postgres
    container_name: maag_app_local_postgres
    ports:
      - "5432:5432"
    volumes:
      - maag_app_local_postgres_data:/var/lib/postgresql/data
      - maag_app_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - maag-network

  docs:
    image: maag_app_local_docs
    container_name: maag_app_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./maag_app:/app/maag_app:z
    ports:
      - '9000:9000'
    networks:
      - maag-network
    command: /start-docs

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: maag_app_local_mailhog
    ports:
      - "8025:8025"
    networks:
      - maag-network

  redis:
    image: redis:6
    container_name: maag_app_local_redis
    networks:
      - maag-network

  celeryworker:
    <<: *django
    image: maag_app_local_celeryworker
    container_name: maag_app_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    networks:
      - maag-network
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: maag_app_local_celerybeat
    container_name: maag_app_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    networks:
      - maag-network
    command: /start-celerybeat

  flower:
    <<: *django
    image: maag_app_local_flower
    container_name: maag_app_local_flower
    ports:
      - '5555:5555'
    networks:
      - maag-network
    command: /start-flower

networks:
  maag-network:
    external:
      name: maag-network
