# Generated by Django 4.2.4 on 2023-09-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="quantity",
            new_name="country_qty",
        ),
        migrations.AddField(
            model_name="stock",
            name="stores_qty",
            field=models.IntegerField(default=0),
        ),
    ]
