# Generated by Django 4.2.4 on 2023-09-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0003_stock_week_stock_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="week",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
