# Generated by Django 4.2.4 on 2023-09-06 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("domain", "0002_product_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("quantity", models.IntegerField(default=0)),
                ("amount", models.IntegerField(default=0)),
                (
                    "mcc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="domain.product",
                    ),
                ),
            ],
        ),
    ]
