# Generated by Django 4.2.4 on 2023-09-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="planned",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sales",
            name="week",
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="sales",
            name="year",
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
