# Generated by Django 4.2.4 on 2023-09-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_sales_planned_sales_week_sales_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="week",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sales",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
