# Generated by Django 4.2.4 on 2023-09-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.CharField(default="", max_length=512),
        ),
    ]
