# Generated by Django 4.2.4 on 2023-09-11 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0003_product_carry_over"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="mirror_mcc",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="domain.product",
            ),
        ),
    ]
